from __future__ import annotations

WORLD_WIDTH = 4000
WORLD_HEIGHT = 4000
TILE_SIZE = 16

DEFAULT_ORGANISM_COUNT = 3
ORGANISM_ENERGY_MIN = 400
ORGANISM_ENERGY_MAX = 600
ORGANISM_SIZE_MIN = 7
ORGANISM_SIZE_MAX = 12

TREE_COUNT_MIN = 30
TREE_COUNT_MAX = 40
APPLES_PER_TREE_MIN = 3
APPLES_PER_TREE_MAX = 5
TREE_MIN_DISTANCE = 80.0
TREE_MARGIN = 48.0

FLOWER_COUNT_MIN = 50
FLOWER_COUNT_MAX = 100
FLOWER_MIN_DISTANCE = 16.0
FLOWER_MARGIN = 16.0

FEATURES = ("none", "antena", "rogi", "nogi", "guzki", "skrzydła")

DEFAULT_PROGRAM = (
    "SENSE",
    "IF_FOOD_TOUCH->EAT",
    "IF_ENERGY_HIGH->REPRODUCE",
    "IF_FOOD_NEARBY->MOVE",
    "IF_ENERGY_LOW->WAIT",
)

TERRAIN_GRASS = "grass"
TERRAIN_DIRT = "dirt"
TERRAIN_MEADOW = "meadow"
TERRAIN_HILLS = "hills"
TERRAIN_TYPES = (TERRAIN_GRASS, TERRAIN_DIRT, TERRAIN_MEADOW, TERRAIN_HILLS)

MOVE_COST = 5.0
TURN_COST = 1.0
WAIT_COST = 0.5
SENSE_COST = 2.0

MOVE_STEP = 6.0
TURN_RATE = 0.45
SENSE_RADIUS = 100.0
FOOD_TOUCH_RANGE = 14.0
ENERGY_MAX = 1000.0
CRITICAL_ENERGY = 80.0
EAT_ENERGY = 150.0
EXISTENCE_COST = 0.2
APPLE_RESPAWN_INTERVAL = 200
FERTILITY_DURATION = 500
FERTILITY_RADIUS = 140.0
REPRODUCE_COST = 200.0
CHILD_ENERGY = 100.0
MUTATION_CHANCE = 0.30
POPULATION_CAP = 300
THINK_COST = 1.0
THINK_TICKS = 2
LEARN_UP = 0.1
LEARN_DOWN = 0.1
LEARN_BAD_DELTA = -10.0
SNAPSHOT_INTERVAL = 100
