from __future__ import annotations

WORLD_WIDTH = 4000
WORLD_HEIGHT = 4000
TILE_SIZE = 16

DEFAULT_ORGANISM_COUNT = 3
ORGANISM_ENERGY_MIN = 650
ORGANISM_ENERGY_MAX = 920
ORGANISM_SIZE_MIN = 7
ORGANISM_SIZE_MAX = 12

TREE_COUNT_MIN = 45
TREE_COUNT_MAX = 60
APPLES_PER_TREE_MIN = 5
APPLES_PER_TREE_MAX = 8
TREE_MIN_DISTANCE = 64.0
TREE_MARGIN = 48.0

FLOWER_COUNT_MIN = 50
FLOWER_COUNT_MAX = 100
FLOWER_MIN_DISTANCE = 16.0
FLOWER_MARGIN = 16.0

BUSH_COUNT_MIN = 28
BUSH_COUNT_MAX = 42
BERRIES_PER_BUSH_MIN = 3
BERRIES_PER_BUSH_MAX = 6
BUSH_MIN_DISTANCE = 36.0
BUSH_MARGIN = 40.0
BERRY_ENERGY = 90.0
BERRY_RESPAWN_INTERVAL = 50

DEFAULT_PROGRAM = (
    "SENSE",
    "IF_FOOD_TOUCH->EAT",
    "IF_ENERGY_HIGH->REPRODUCE",
    "IF_FOOD_NEARBY->MOVE",
    "IF_ENERGY_LOW->WAIT",
)

TERRAIN_GRASS = "grass"
TERRAIN_DIRT = "dirt"
TERRAIN_MEADOW = "meadow"
TERRAIN_HILLS = "hills"
TERRAIN_TYPES = (TERRAIN_GRASS, TERRAIN_DIRT, TERRAIN_MEADOW, TERRAIN_HILLS)

MOVE_COST = 3.0
TURN_COST = 1.0
WAIT_COST = 0.5
SENSE_COST = 2.0

MOVE_STEP = 6.0
MAX_SPEED = 12.0
ACCEL_AMOUNT = 2.0
SPEED_DECAY = 0.72
TURN_RATE = 0.45
SENSE_RADIUS = 220.0
FOOD_TOUCH_RANGE = 14.0
FOOD_MEMORY_TICKS = 90
ENERGY_MAX = 1800.0
CRITICAL_ENERGY = 80.0
EAT_ENERGY = 220.0
WELL_FED_ENERGY = 1000.0
COMFORT_ENERGY = 420.0
HUNGER_DROP_MIN = 0.10
HUNGER_DROP_SPAN = 0.20
SHARE_TOUCH_RANGE = 20.0
MATE_RANGE = 28.0
CACHE_DROP_RANGE = 28.0
BODY_RADIUS_SCALE = 1.15
BOUNCE_RESTITUTION = 0.85
BOUNCE_IMPULSE = 5.0
PILLAR_RADIUS = 22.0
PILLAR_CLEARING = 72.0
WIND_RADIUS_RATIO = 0.13
WIND_STRENGTH = 2.4
WIND_COST_FACTOR = 0.35
APPLE_WIND_SCALE = 0.55
EXISTENCE_COST = 0.2
APPLE_RESPAWN_INTERVAL = 80
FERTILITY_DURATION = 500
FERTILITY_RADIUS = 140.0
REPRODUCE_COST = 200.0
REPRODUCE_COOLDOWN = 45
CHILD_ENERGY = 400.0
MUTATION_CHANCE = 0.30
POPULATION_CAP = 300
THINK_COST = 1.0
THINK_TICKS = 2
LEARN_UP = 0.1
LEARN_DOWN = 0.1
LEARN_BAD_DELTA = -10.0
SNAPSHOT_INTERVAL = 100
